### ISSUE TITLE
Upper part of wooden plank has invalid depth (Arroyo).

### ISSUE THREAD

**Issue by Risu** [BGforgeNet/Fallout2_Unofficial_Patch#15]
I am playing RPUv6, but this should affect UPU too.
Everything dropped on upper part of plank disappears.
Wilderness Arroryo:
![plank_depth](https://user-images.githubusercontent.com/5950603/62402830-fe1d7080-b589-11e9-8eb5-0e3b18d024c2.png)

**Comment by burner1024** [comment]
1. I think we can omit "something else" from issue titles, it doesn't carry much information.
2. I'm actually not sure how/if this can be fixed. I'm not too familiar with mapper.
3. If you know, you can submit pull requests for this and any other issues.

**Comment by Risu** [comment]
> 1. I think we can omit "something else" from issue titles, it doesn't carry much information.
Unbolding "Something else" in instruction will clarify that it's not a tag.

**Comment by burner1024** [comment]
done

**Comment by burner1024** [comment]
It is my understanding that "[Flat](https://falloutmods.fandom.com/wiki/PRO_File_Format#Common_header)" flag should take care of this.
However, it's already enabled for the plank. Disabling it indeed makes it so that items dropped on the _lower_ part of the plank also become invisible.
Looks like an engine issue? I'd try running this by sfall guys. Until then, I don't really know what to do with this, so adding a note and closing.
