### ISSUE TITLE
Killap's crowbar/trap code for locked doors isnt working properly

### ISSUE THREAD

**Issue by Question2** [BGforgeNet/Fallout2_Unofficial_Patch#61]
Using v18 RPU with sfall v4.2.8.

I noticed that Killap added code to many locked doors to allow you to force them open with a crowbar or trap them with dynamite/plastic explosive, however I also noticed that this doesnt appear to work properly.

For example, when trying to use a crowbar on the locked door in the klamath rat caves leading to the fuel cell regulator, you only get the message "this does nothing". The same happens if you attempt to use dynamite on it.

For reference, this is from KSCVDOOR.ssl : 

```
procedure use_obj_on_p_proc begin
   variable Tool;

   Tool:=obj_pid(obj_being_used_with);


    if (LOCK_STATUS == STATE_STANDARD_LOCK) then begin
       if (Tool == PID_LOCKPICKS) then begin
           script_overrides; //added by killap
           if (local_var(LVAR_Locked) == STATE_ACTIVE) then begin
               call Lockpick_Lock;
           end
           else begin
               call Set_Lockpick_Lock;
           end
       end
       //added by killap
       else if (Tool == PID_EXP_LOCKPICK_SET) then begin
            script_overrides; //added by killap
            if (local_var(LVAR_Locked) == STATE_ACTIVE) then begin
               call Super_Lockpick_Lock;
            end
            else begin
               call Super_Set_Lockpick_Lock;
            end
       end
       //end added by killap
   end

   else if (LOCK_STATUS == STATE_ELECTRIC_LOCK) then begin
       if (Tool == PID_ELECTRONIC_LOCKPICKS) then begin
           script_overrides; //added by killap
           if (local_var(LVAR_Locked) == STATE_ACTIVE) then begin
               call Lockpick_Lock;
           end
           else begin
               call Set_Lockpick_Lock;
           end
       end
       //added by killap
       else if (Tool == PID_ELEC_LOCKPICK_MKII) then begin
           script_overrides; //added by killap
           if (local_var(LVAR_Locked) == STATE_ACTIVE) then begin
               call Super_Lockpick_Lock;
           end
           else begin
               call Super_Set_Lockpick_Lock;
           end
       end
       //end added by killap
   end

   else if (Tool == PID_CROWBAR) then begin
       script_overrides; //added by killap
       call Pry_Door;
   end

   else if ((Tool == PID_DYNAMITE) or (Tool == PID_PLASTIC_EXPLOSIVES)) then begin
       script_overrides; //added by killap
       call Set_Trap;
   end

end
```

The last two blocks with the crowbar and dynamite never get called at all. I tried moving those two to the top of the procedure and it did work though, i was able to use a crowbar to bust open the lock and i was able to attempt to trap the door with dynamite. For some reason, the dynamite simply dissapeared from my inventory when i failed to set the trap, im not sure if this is intended as it never dissapears when you arm it in your inventory, even if you have very low trap skill. The only way you can fail to arm dynamite is the risk of premature detonation.

So for example changing the procedure to this will allow the crowbar/dynamite code to work : 

```
procedure use_obj_on_p_proc begin
   variable Tool;

   Tool:=obj_pid(obj_being_used_with);

   if (Tool == PID_CROWBAR) then begin
       script_overrides; //added by killap
       call Pry_Door;
   end

   else if ((Tool == PID_DYNAMITE) or (Tool == PID_PLASTIC_EXPLOSIVES)) then begin
       script_overrides; //added by killap
       call Set_Trap;
   end

   else if (LOCK_STATUS == STATE_STANDARD_LOCK) then begin
       if (Tool == PID_LOCKPICKS) then begin
           script_overrides; //added by killap
           if (local_var(LVAR_Locked) == STATE_ACTIVE) then begin
               call Lockpick_Lock;
           end
           else begin
               call Set_Lockpick_Lock;
           end
       end
       //added by killap
       else if (Tool == PID_EXP_LOCKPICK_SET) then begin
            script_overrides; //added by killap
            if (local_var(LVAR_Locked) == STATE_ACTIVE) then begin
               call Super_Lockpick_Lock;
            end
            else begin
               call Super_Set_Lockpick_Lock;
            end
       end
       //end added by killap
   end

   else if (LOCK_STATUS == STATE_ELECTRIC_LOCK) then begin
       if (Tool == PID_ELECTRONIC_LOCKPICKS) then begin
           script_overrides; //added by killap
           if (local_var(LVAR_Locked) == STATE_ACTIVE) then begin
               call Lockpick_Lock;
           end
           else begin
               call Set_Lockpick_Lock;
           end
       end
       //added by killap
       else if (Tool == PID_ELEC_LOCKPICK_MKII) then begin
           script_overrides; //added by killap
           if (local_var(LVAR_Locked) == STATE_ACTIVE) then begin
               call Super_Lockpick_Lock;
           end
           else begin
               call Super_Set_Lockpick_Lock;
           end
       end
       //end added by killap
   end

end
```

I can still use lockpicks on the door as well.

Save in the rat caves if you want to test it : 

[SLOT03.zip](https://github.com/BGforgeNet/Fallout2_Restoration_Project/files/5766509/SLOT03.zip)

**Comment by burner1024** [comment]
phew, this is taxing

**Comment by burner1024** [comment]
OK, this turned out to be quite harder than expected. I've shoved a shit ton (and that is a literal shit) of code. Due to copy paste abuse, the code variations are very similar, but different just enough to make mass replace impossible, and reusage hard. And the scope creeps all the time you work on it. I had to restart from scratch 2 times to keep it under control.

Multiple issues preventing from creating a "perfect" template from scratch, for reference and as a reminder to myself:
1. Many scripts have customized procedures.
2. Doors and containers share a lot of similar code. But they don't share the messages.
3. On top of that, some doors and containers use non-standard message files.
3. Most doors use `LVAR_Locked` to remember their locked state. For some reason, `ziwoddor` doesn't. It checks `obj_locked` directly. However, in my testing, object locked state doesn't survive map travel. `ziwoddor` is used as a template for multiple doors. This will need to be tested again and acted upon separately.
  Also, `LVAR_Locked` is the first LVAR, and removing it will mess up savegames. Not removing will not allow to unify the code.
4. To allow custom procedures, standard ones should be added to the bottom of the script. But sharing code for custom procedures requires it to be included at the top.

Anyway, here's the current situation:
1. Doors have 2 headers: doors.h and doors2.h. First one contains pieces of code as defines should be included at the top, second one serves as a template with standard procedures and should be included at the bottom.
2. Some code between doors and containers headers is the same.
3. `ziwoddor` is basically unchanged, serving as a template for several other scripts.
4. The code is split between `doors.h`, `door2.h`, `containers.h`, `containers2.h`, `ziwoddor.ssl` and custom procedures in scripts.

I only consolidated a few procedures for now. Others can be dealt with if and when situation requires. It's still ugly, but in fewer places. Not meant to be perfect, just something to start with.

There's been a lot of commits, so I ran some extra checks in the end:
```
$ diff -u scripts.0 scripts.3
Binary files scripts.0/containr.int and scripts.3/containr.int differ
Binary files scripts.0/dichcdor.int and scripts.3/dichcdor.int differ
Binary files scripts.0/didoor.int and scripts.3/didoor.int differ
Binary files scripts.0/diflkbox.int and scripts.3/diflkbox.int differ
Binary files scripts.0/dipendor.int and scripts.3/dipendor.int differ
Binary files scripts.0/direbdor.int and scripts.3/direbdor.int differ
Binary files scripts.0/diromdor.int and scripts.3/diromdor.int differ
Binary files scripts.0/divicdor.int and scripts.3/divicdor.int differ
Binary files scripts.0/door.int and scripts.3/door.int differ
Binary files scripts.0/hscrldr.int and scripts.3/hscrldr.int differ
Binary files scripts.0/iilockdr.int and scripts.3/iilockdr.int differ
Binary files scripts.0/kibbox.int and scripts.3/kibbox.int differ
Binary files scripts.0/kidbox.int and scripts.3/kidbox.int differ
Binary files scripts.0/kisbox.int and scripts.3/kisbox.int differ
Binary files scripts.0/midoor.int and scripts.3/midoor.int differ
Binary files scripts.0/nibishdr.int and scripts.3/nibishdr.int differ
Binary files scripts.0/nidoor.int and scripts.3/nidoor.int differ
Binary files scripts.0/nielddor.int and scripts.3/nielddor.int differ
Binary files scripts.0/nimyrdor.int and scripts.3/nimyrdor.int differ
Binary files scripts.0/nisaldor.int and scripts.3/nisaldor.int differ
Binary files scripts.0/niwridor.int and scripts.3/niwridor.int differ
Binary files scripts.0/sidtbl.int and scripts.3/sidtbl.int differ
Binary files scripts.0/simbox.int and scripts.3/simbox.int differ
Binary files scripts.0/siptbox.int and scripts.3/siptbox.int differ
Binary files scripts.0/siptbox2.int and scripts.3/siptbox2.int differ
Binary files scripts.0/vivltdr2.int and scripts.3/vivltdr2.int differ
Binary files scripts.0/ziwoddor.int and scripts.3/ziwoddor.int differ
```

**Comment by burner1024** [comment]
With this, we're down from 51 to 18 invocations of `Pry_Door`, which can probably be reduced further while working on the actual reported bug.

**Comment by burner1024** [comment]
almost there... last things I want to add is actual explosion graphics on setting of a trap and maybe let prying to set them off as well.

**Comment by burner1024** [comment]
wanted to add magic hands animations on trapping the door, but it doesn't work great ref https://github.com/rotators/Fo1in2/issues/70
