### ISSUE TITLE
"I can't do that"

### ISSUE THREAD

**Issue by Lexx2k** [BGforgeNet/Fallout2_Unofficial_Patch#77]
The message is printed into the log when trying to use weapons for which the player character has no animations.

My issue with that is that it's ... not in style with the rest of the game. I think it would be better written as either "You can't do that." or if more precise "You can't equip that." or "You can't use that right now."

I've only noticed that in the UP files, so I'm not 100% sure if that's an Sfall thing or part of the patch.

/Edit: Oh, I just tested it in ettu and it indeed seems to be an Sfall thing. :>

![scr00001](https://user-images.githubusercontent.com/4844938/117981189-07c63180-b335-11eb-8108-3ec5f03701d7.png)

**Comment by burner1024** [comment]
Yes, must an sfall thing.
I think that the message could be improved, but I would not get it in style. On the contrary, I'd rather clearly communicate to the player that this critter has no corresponding animation for this weapon. Maybe even specifically prefix it with `sfall | error: ...`.

(Since the only way you can achieve that is by cheating, I see no problem with breaking "style". But I'd rather prefer it to be extra clear, to avoid any confusion what happened and where is the messagfe from. I mean - even you didn't realize at first it was originating from sfall.)
