### ISSUE TITLE
No Support for Foreign Accents or Upscaling the GUI

### ISSUE THREAD

**Issue by Felipefpl** [BGforgeNet/Fallout2_Unofficial_Patch#79]
A problem found in Falllout is that accents in the letters like "ã" , "ê" or "ú" arent displayed correctly in the game, the letters with those accents have their size reduced and look ugly.

Another problem is the fact the GUI doesnt upscale which forces decreasing the size of the words to avoid the words being showed outside the GUI, only way to avoid this is using synonyms or abbreviations (which many times look ugly like those letters with accents).

**Comment by Lexx2k** [comment]
Scalable interface for the text isn't possible / very unlikely to ever happen. 

For the letters, someone needs to make new font files.

**Comment by burner1024** [comment]
1. This is how the fonts are. I'm not planning to do anything about this, however if a pull improving this were submitted, I'd accept it.
  If this issue annoys you, try searching NMA for fonts discussions, and font editors. Since all letters with accents are dwarfed, there might be an engine reason for that, I don't know, you'll have to try.
2. I'm not sure what do you mean, a screenshot would help.

**Comment by Lexx2k** [comment]
>     2\. I'm not sure what do you mean, a screenshot would help.

Some button text can end up too long for the interface graphic and then the text has to be shortened in the translation.
That's actually one of the reasons why the german version has a narrower font for some UI elements.

**Comment by burner1024** [comment]
One could try to scale the interface graphic itself, but I'm not sure that'd be enough, and anyway out of patch scope, too.
