### ISSUE TITLE
Complete package

### ISSUE THREAD

**Issue by burner1024** [BGforgeNet/Fallout2_Unofficial_Patch#9]
Turning UPU into a complete package should be relatively simple.
- There's no options, and with new sfall there's no need for repackaging dat files.
- I see no need to bother with pre-XP systems.
- I also see no need for a GUI installer. (Even if I did, that'd hard to build, as I have no access to a windows environment).

So, I think a script deleting patch000.dat and data directory should be just enough. Or, tell users to do that manually?

**Comment by burner1024** [comment]
There's also HRP, though. Are d3dx dlls needed? All of them?
And, is it better to include f2_res_patcher, or just provide fallout2.exe already patched?

**Comment by NovaRain** [comment]
> So, I think a script deleting patch000.dat and data directory should be just enough. Or, tell users to do that manually?

I think it should be clearing everything other than `Data\savegame` (UP saves should be compatible between versions after 1.02.25, just map fixes won't apply for visited maps) and `Data\sound\music` in data directory.

The music folder has an interesting background history:
* In original CD installation, the music files are installed in `<GameRoot>\Data\sound\music\`.
* For some reason GOG's first release (when Interplay still held the right of selling classic FO games) put the music files in `<GameRoot>\sound\music`, which causeed no music in the game because paths in cfg still point to `data\sound\music`. The later releases fixed the issue by editing paths in cfg, not moving the music back to the original directory. And now it becomes the standard in all digital releases. (Bethesda's re-release is based on GOG with adding a fancy launcher and HRP-ready fallout2HR.exe.)

That's why RP installer includes a script to change the music_path1/2 in cfg to support both cases.

**Comment by burner1024** [comment]
You're right about savegames and other stuff.
Changing music path is easy in bash, but I'd have to look up how to do it in bat.

**Comment by burner1024** [comment]
pretty much done
