### ISSUE TITLE
ectravlr dialog issues

### ISSUE THREAD

**Issue by Lexx2k** [BGforgeNet/Fallout2_Unofficial_Patch#99]
[This dialog](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/28332ebe1035df1436cd4ba6aeaf4bbbaaaddd56/scripts_src/rndenctr/ectravlr.ssl#L367) seems broken.

![scr00008](https://user-images.githubusercontent.com/4844938/178299214-13f00c22-6e08-4506-9dda-7415e5d9250d.png)

The whole flow is weird / mixed up - see the screenshot, that can't be right. It just keeps going incomprehensible after that, as if someone shifted the line numbers. 

Stumbled over the encounter ("You encounter: a Traveller") at random around New Reno.

**Comment by lanhdongls** [comment]
Isn't this intended? If you keep pressing her on where she's headed she will refuse to talk to you and say you have "broken the traveller's code".

**Comment by burner1024** [comment]
you have a save?

**Comment by Lexx2k** [comment]
Here:
[SLOT14.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/9089440/SLOT14.zip)

The encounter is actually quite common around New Reno.

**Comment by burner1024** [comment]
It's RP script, there's mentions of EPA.

**Comment by Lexx2k** [comment]
Then it accidentally slipped into the UP? I also remember a traveler encounter that would give you the location of SAD, but dunno if it's the same or a different one (also don't remember if it was only in the RP.. haven't played it in many years).

**Comment by burner1024** [comment]
In UP source, at least. Too lazy to check the decompiled script.

Not sure why adding a single new zone option would require changing the whole script file. Need to check and probably rewrite this in a less intrusive way.

**Comment by burner1024** [comment]
ok,
1. It's actually [ectrvlr](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/scripts_src/rndenctr/ectrvlr.ssl), not [ectravlr](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/master/scripts_src/rndenctr/ectravlr.ssl). As far as I can see, the scripts are identical and are using the same msg file. Not sure if `ectravlr` is used (but it's registered in `scripts.lst`).
2. The reason why dialog numbers differ is because available locations are calculated in the script with random, so killap inserted EPA , shifting all consequtive line numbers.
3. I just used RP script/msg as base, shifted location lines to a separate range and edited out EPA, so now scripts and messages are much more convergent between UPU/RPU.
4. Also cleaned up the scripts and fixed combat taunts.
[fix.zip](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/files/9094733/fix.zip)

**Comment by Lexx2k** [comment]
Just tested it, works now.
